# -*- mode: ruby -*-
# vi: set ft=ruby :

$workers=1
Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
  config.vm.provider :libvirt do |libvirt|
    libvirt.graphics_ip = '0.0.0.0'
    libvirt.cpus = 4
    libvirt.memory = 8192
    libvirt.machine_virtual_size = 200
  end

  config.vm.define "master" do |config|
    config.vm.hostname = "master"
    config.vm.provision "shell", path: "bootstrap.sh"
    config.vm.provision "shell", path: "install-kub.sh"
#    config.vm.provision "shell", path: "kubeadm-init.sh"
  end
  (1 .. $workers).each do |n|
    config.vm.define vm_name = "worker#{n}" do |config|
      config.vm.hostname = vm_name
      config.vm.provision "shell", path: "bootstrap.sh"
      config.vm.provision "shell", path: "install-kub.sh"
      #config.vm.provision "shell", path: "kubeadm-join.sh"
    end
  end
end
