# -*- mode: ruby -*-
# vi: set ft=ruby :

$nodes=2
Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
  config.vm.provider :libvirt do |libvirt|
    libvirt.graphics_ip = '0.0.0.0'
    libvirt.cpus = 4
    libvirt.memory = 8192
    libvirt.machine_virtual_size = 200
  end

  config.vm.define "deployer" do |config|
    config.vm.hostname = "kubdeployer"
    config.vm.synced_folder ".", "/nfs", type: "nfs"
    config.vm.provision "shell", path: "bootstrap.sh"
  end
  (1 .. $nodes).each do |n|
    config.vm.define vm_name = "kub#{n}" do |config|
      config.vm.hostname = vm_name
      config.vm.provision "shell", path: "bootstrap.sh"
    end
  end
end
