network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: true
      dhcp6: false
      optional: true
      nameservers:
        addresses: [10.96.0.10, 10.239.27.228]
        search: [svc.cluster.local, cluster.local]
