# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos7"
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
  config.vm.synced_folder ".", "/nfs", type: "nfs"
  config.vm.provision "shell", path: "bootstrap.sh"
  config.vm.network "private_network", type: "dhcp", libvirt__network_address: "192.168.123.0"
  config.vm.provider :libvirt do |libvirt|
    libvirt.graphics_ip = '0.0.0.0'
    libvirt.cpus = 4
    libvirt.memory = 8192
    libvirt.machine_virtual_size = 200
  end

  config.vm.define "default" do |config|
    config.vm.hostname = 'smb'
    config.vm.provision "shell", path: "samba.sh"
  end

  (1 .. 0).each do |n|
    config.vm.define vm_name = "centos#{n}" do |config|
      config.vm.hostname = vm_name
    end
  end

end
