# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1604"
  config.vm.hostname = "ubuntu16"
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
  #config.vm.synced_folder ".", "/nfs", type: "nfs"
  config.vm.provision "shell", path: "bootstrap.sh"
  config.vm.provider :libvirt do |libvirt|
    libvirt.graphics_ip = '0.0.0.0'
    libvirt.disk_device = 'sda'
    libvirt.cpus = 4
    libvirt.memory = 8192
    libvirt.machine_virtual_size = 200
  end

  config.vm.define "default" do |config|
    config.vm.hostname = 'ubuntu16'
  end

  (1 .. 0).each do |n|
    config.vm.define vm_name = "xenial#{n}" do |config|
      config.vm.hostname = vm_name
    end
  end

end
