# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1604"
  config.vm.hostname = "ubuntu16"
  config.vm.synced_folder ".", "/vagrant"
  config.vm.provision "shell", path: "bootstrap.sh"
  config.vm.provider :libvirt do |libvirt|
    libvirt.graphics_ip = '0.0.0.0'
    libvirt.cpus = 4
    libvirt.memory = 8192
    libvirt.machine_virtual_size = 200
  end
  (1 .. 1).each do |n|
    config.vm.define vm_name = "node#{n}" do |config|
      config.vm.hostname = vm_name
    end
  end

end
