# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  #config.vm.box = "generic/centos7"
  #config.vm.synced_folder ".", "/vagrant", type: "rsync"
  #config.vm.synced_folder ".", "/nfs", type: "nfs"

  config.vm.define "default" do |config|
    config.vm.hostname = 'isocentos'
    config.vm.network "private_network", type: "dhcp", libvirt__network_address: "192.168.123.0"
    config.vm.provider :libvirt do |libvirt|
      libvirt.graphics_ip = '0.0.0.0'
      libvirt.cpus = 8
      libvirt.memory = 18192
      #libvirt.machine_virtual_size = 200
      libvirt.storage :file, :device => :cdrom, :path => '/home/cheng/bootstrap/isovm/CentOS-7-x86_64-Everything-1810.iso'
      libvirt.storage :file, :size => '20G', :path => "ivmdisk.img", :allow_existing => true
      libvirt.boot 'hd'
      libvirt.boot 'cdrom'
    end
  end

  (1 .. 2).each do |n|
    config.vm.define vm_name = "iso#{n}" do |config|
      config.vm.hostname = vm_name
    config.vm.network "private_network", type: "dhcp", libvirt__network_address: "192.168.123.0"
      config.vm.provider :libvirt do |libvirt|
        libvirt.graphics_ip = '0.0.0.0'
        libvirt.cpus = 8
        libvirt.memory = 18192
        libvirt.storage :file, :device => :cdrom, :path => '/home/cheng/bootstrap/isovm/CentOS-7-x86_64-Everything-1810.iso'
        libvirt.storage :file, :size => '20G', :path => "ivmdisk#{n}.img", :allow_existing => true
        libvirt.boot 'hd'
        libvirt.boot 'cdrom'
      end

    end
  end

end
