# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # config.vm.guest = "centos"
  config.vm.box = "ctyunos"
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
  #config.vm.synced_folder ".", "/nfs", type: "nfs"
  config.vm.provision "shell", path: "bootstrap.sh"
  config.vm.network "private_network", libvirt__network_name: "private-123", type: "dhcp", libvirt__network_address: "192.168.123.0/255.255.255.0"
  config.vm.network "private_network", libvirt__network_name: "private-129", type: "dhcp", libvirt__network_address: "192.168.120.0/255.255.255.0"
  config.vm.provider :libvirt do |libvirt|
    libvirt.graphics_ip = '0.0.0.0'
    libvirt.cpus = 12
    libvirt.memory = 18192
    # libvirt.machine_virtual_size = 20
  end

  config.vm.define "default" do |config|
    config.vm.hostname = 'ctyunos'
  end

  (1 .. 0).each do |n|
    config.vm.define vm_name = "centos#{n}" do |config|
      config.vm.hostname = vm_name
    end
  end

end
