# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.box_version = "1811.01"
  config.vm.hostname = "centos7"
  #config.vm.synced_folder ".", "/nfs", type: "nfs"
  config.vm.network "private_network", type: "dhcp", libvirt__network_address: "192.168.123.0"
  config.vm.provision "shell", path: "bootstrap.sh"
  config.vm.provision "shell", path: "osa.sh"
  config.vm.provider :libvirt do |libvirt|
    libvirt.graphics_ip = '0.0.0.0'
    libvirt.cpus = 4
    libvirt.memory = 8164
    libvirt.machine_virtual_size = 80
  end
  config.vm.define "deployer" do |config|
    config.vm.hostname = 'deployer'
  end
  # we can't deploy haproxy and os services on the same node
  # so we need at least 2 nodes
  (1 .. 2).each do |n|
    config.vm.define vm_name = "osa#{n}" do |config|
      config.vm.hostname = vm_name
    end
  end

end
