# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos7"
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
  # config.vm.synced_folder ".", "/nfs", type: "nfs"
  config.vm.network "private_network", libvirt__network_name: "private-123", type: "dhcp", libvirt__network_address: "192.168.123.0/255.255.255.0"
  config.vm.network "private_network", libvirt__network_name: "private-124", type: "dhcp", libvirt__network_address: "192.168.124.0/255.255.255.0"
  config.vm.provision "shell", path: "bootstrap.sh"
  config.vm.provider :libvirt do |libvirt|
    libvirt.graphics_ip = '0.0.0.0'
    libvirt.cpus = 8
    libvirt.memory = 8164
    libvirt.machine_virtual_size = 20
  end
  config.vm.define "ovnmaster" do |config|
    config.vm.hostname = 'ovnmaster'
    config.vm.provision "shell", path: "ovn-controller-init.sh"
  end
  (1 .. 2).each do |n|
    config.vm.define vm_name = "ovn#{n}" do |config|
      config.vm.hostname = vm_name
      config.vm.provision "shell", path: "ovn-host-init.sh"
    end
  end
end
